# Translates foreign map names into English
# Map totals from 1v1 -> FFA: 9, 9, 9, 7, 6
MAP_LOCALIZATIONS = {
	# KOREAN
	# Missing: Burial Grounds, Worldship, Debris Field, Nightmare, Terminus, Red Stone Gulch, Dirt Side, Forbidden Planet
	"폭염 사막 초보자용" => "Novice Blistering Sands",
	"사막 오아시스 초보자용" => "Novice Desert Oasis",
	"전쟁 초원 초보자용" => "Novice Steppes of War",
	"쿨라스 협곡 초보자용" => "Novice Kulas Ravine",
	"금속도시 초보자용" => "Novice Scrap Station",
	"불협화음 IV 초보자용" => "Novice Discord IV",
	"몬리스 마루" => "Monlyth Ridge",
	"황혼 요새 초보자용" => "Novice Twilight Fortress",
	"몬리스 마루 초보자용" => "Novice Monlyth Ridge",
	"십자포화" => "Crossfire",
	"아그리아 골짜기" => "Agria Valley",
	"샤쿠라스 고원" => "Shakuras Plateau",
	"고물 처리장" => "Junk Yard",
	"소각 지대" => "Incineration Zone",
	"밀림 분지" => "Jungle Basin",
	"금속도시" => "Metalopolis",
	"쿨라스 협곡" => "Kulas Ravine",
	"심연" => "Abyss",
	"젤나가 동굴" => "Xel'Naga Caverns",
	"사막 오아시스" => "Desert Oasis",
	"고철 처리장" => "Scrap Station",
	"전쟁 초원" => "Steppes of War",
	"델타 사분면" => "Delta Quadrant",
	"잃어버린 사원" => "Lost Temple",
	"폭염 사막" => "Blistering Sands",
	"폭풍우 전장" => "Tempest",
	"전쟁 지역" => "War Zone",
	"잿더미 안식처" => "Scorched Haven",
	"메마른 황무지" => "Arid Wastes",
	"황혼 요새" => "Twilight Fortress",
	"불협화음 IV" => "Discord IV",
	"고궤도" => "High Orbit",
	"타소니스 공습" => "Tarsonis Assault",
	"변경 지대" => "Frontier",
	"계절풍 지대" => "Monsoon",
	"울란의 심연" => "Ulaan Deeps",
	"426 거주지" => "Colony 426",
	"아라칸 요새" => "Arakan Citadel",
	"모래늪" => "Quicksand",
	"티폰" => "Typhon",
	"발굴지" => "Dig Site",
	"생체 실험실" => "The Bio Lab",
	"모래 협곡" => "Sand Canyon",
	"독지대" => "Toxic Slums",
	"메가톤" => "Megaton",
	"용암 흐름" => "Lava Flow",
	"고지대" => "High Ground",
	"전초 기지" => "Outpost",
	"절멸" => "Extinction",
	"엘리시움" => "Elysium",

	# TW, Chinese
	"庫拉斯溪谷（新手）" => "Novice Kulas Ravine",
	"大都會（新手）" => "Novice Metalopolis",
	"太空總站（新手）" => "Novice Scrap Station", # Not 100%
	"極熱沙漠（新手）" => "Novice Blistering Sands",
	"戰爭平原（新手）" => "Novice Steppes of War",
	"沙漠綠洲（新手）" => "Novice Desert Oasis",
	"紛爭 IV（新手）" => "Novice Discord IV",
	"蒙利斯山脈（新手）" => "Novice Monlyth Ridge",
	"暮光堡壘（新手）" => "Novice Twilight Fortress",

	"阿格利亞山谷" => "Agria Valley",
	"426區殖民地" => "Colony 426",
	"叢林盆地" => "Jungle Basin",
	"夢靨" => "Nightmare",
	"沙漠綠洲" => "Desert Oasis",
	"交叉火力" => "Crossfire",
	"無盡深淵" => "Abyss", # Not 100%
	"死亡墓園" => "Burial Grounds",
	"廢料處理站" => "Scrap Station",
	"庫拉斯溪谷" => "Kulas Ravine",
	"戰爭平原" => "Steppes of War",
	"薩爾納加洞穴" => "Xel'Naga Caverns",
	"極熱沙漠" => "Blistering Sands",
	"失落神廟" => "Lost Temple",
	"第四象限" => "Delta Quadrant",
	"大都會" => "Metalopolis",
	"戰爭特區" => "War Zone",
	"高軌道區" => "High Orbit",
	"暮光堡壘" => "Twilight Fortress",
	"塔桑尼斯突擊戰" => "Tarsonis Assault",
	"大風暴" => "Tempest",
	"海文焦土" => "Scorched Haven",
	"紛爭 IV" => "Discord IV",
	"蒙利斯山脈" => "Monlyth Ridge",
	"不毛荒地" => "Arid Wastes",
	"鈦風" => "Tectonic Rift",
	"生物實驗室" => "The Bio Lab",
	"阿洛坎要塞" => "Arakan Citadel",
	"挖掘場" => "Dig Site",
	"流沙" => "Quicksand",
	"邊疆地帶" => "Frontier",
	"季風雨林" => "Monsoon",
	"烏蘭深穴" => "Ulaan Deeps",
	"塵沙峽谷" => "Sand Canyon",
	"滅絕" => "Extinction",
	"哨站" => "Outpost",
	"梅迦鎮" => "Megaton",
	"毒窟" => "Toxic Slums",
	"高地" => "High Ground",
	"熔漿岩地" => "Lava Flow",
}

BLIZZARD_MAPS = {}
MAP_LOCALIZATIONS.values.each do |map|
	BLIZZARD_MAPS[map] = true
end