#!/usr/bin/env ruby-worker-env
RAILS_ROOT = File.expand_path(File.join(File.dirname(__FILE__), "..", ".."))
Dir.chdir(RAILS_ROOT)
require "rubygems"
require "#{RAILS_ROOT}/config/environment.rb"

total = Armory::Job.count() || 0
to_update = total > 10000 && 50 || total > 6000 && 500 || total > 3000 && 1000 || 5000

puts "Updating #{to_update} characters"

list = []
Character.all(:limit => to_update, :order => "updated_at ASC").each do |character|
	list.push({:region => character.region, :bnet_id => character.bnet_id, :name => character.name})
end

# Fill out what we didn't get from null character codes, with old players
#if list.length < to_update
#	Character.all(:limit => to_update - list.length, :order => "updated_at ASC").each do |character|
#		list.push({:region => character.region, :bnet_id => character.bnet_id, :name => character.name})
#	end
#end

Armory::Queue.mass_array_characters(list)
