#!/usr/bin/env ruby
RAILS_ROOT = File.expand_path(File.join(File.dirname(__FILE__), ".."))
Dir.chdir(RAILS_ROOT)
require "rubygems"
require "#{RAILS_ROOT}/config/environment.rb"

offset = 0
has_data = true

#SELECT COUNT(*) as total, region, bracket, hash_id FROM teams GROUP BY region, bracket, hash_id HAVING COUNT(*) > 1;
while( has_data ) do
	has_data = nil
	Team.all(:conditions => ["old_hash_id is null"], :limit => 5000, :offset => offset).each do |team|
		has_data = true
		puts "Cleaning team #{team.id}"

		team.delete
		TeamCharacter.delete_all(["team_id = ?", team.id])
	end
	
	offset += 5000
end